'use strict';
const $=id=>document.getElementById(id),KEY='mattbear-enzo-v1',HASH='cf23dc33d6aba13592a72190564ed18b2c0dae295f681ee0fddc4862f01225cf';
let original,data,settings={guided:true,strict:true,reference:true},stats={served:0,buildAttempts:0,buildCorrect:0,quizTests:0,quizAnswers:0,quizCorrect:0,best:0},admin=false,active='game';
let recipe,applied=[],prepared=false,completed=false,counted=false,attempts=0,mistakes=0,startTime=0,ticketNumber=1,hintShown=false,quiz={questions:[],index:0,answers:[],answered:false};
const crusts=['Not specified','Sesame','Ranch','Buffalo ranch','Everything bagel','Chili lime','Garlic butter parmesan','Garlic herb'];
const ingredientArt={};
const atlasRows={toppings:['Pepperoni','Ham','Sausage','Beef','Bacon','Grilled chicken','Shaved ribeye','Mushroom','Onion','Red onion','Green pepper','Black olive','Green olive','Tomato','Banana peppers','Jalapeño'],specialties:['Mozzarella','Fresh mozzarella','Monterey cheddar','Cotija cheese','Pineapple','Sweet corn','Pickles','Lettuce','Basil','Dill','Scallions','Crispy wontons','Crab','Scrambled egg','Sausage gravy','Pizza sauce'],sauces:['Ranch drizzle','Garlic cream cheese dip','Alfredo sauce','Vodka sauce','BBQ sauce','Buffalo sauce','Korean BBQ sauce','Honey','Balsamic glaze','Lemon aioli','Mayo','Special sauce','Herbs','Chili powder blend','Fat ranch','Super secret sauce']};
for(const [atlas,names]of Object.entries(atlasRows))names.forEach((name,i)=>ingredientArt[name]={atlas,index:i});
for(const [name,target]of [['Cup & crisp pepperoni','Pepperoni'],['Extra cheese','Mozzarella'],['Cheese blend','Mozzarella'],['Cheddar','Monterey cheddar'],['Base sauce (confirm with kitchen)','Pizza sauce'],['Base cheese (confirm with kitchen)','Mozzarella'],['Chicken','Grilled chicken'],['Jalapeno','Jalapeño']])ingredientArt[name]=ingredientArt[target];
const allIngredients=()=>[...new Set(data.items.flatMap(i=>i.ingredients))];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shuffle(arr){arr=[...arr];for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]];}return arr;}
function readStore(){try{return JSON.parse(localStorage.getItem(KEY))||{};}catch{return {};}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({items:data.items,settings,stats}));return true;}catch{$('admin-feedback').textContent='Browser storage is unavailable. Export your edits to keep them.';return false;}}
async function validCode(code){if(!/^\d{4}$/.test(code))return false;const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(code));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')===HASH;}
function unlocked(){return !$('app').hidden;}
function showView(id){if(!unlocked())return;if(id==='admin-panel'&&!admin)return;active=id;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==id);document.querySelectorAll('.tabs button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tab===id));}
function setFeedback(text,bad=false){$('game-feedback').textContent=text;$('game-feedback').className=bad?'bad':completed?'success':'';}
function artStyle(name){const a=ingredientArt[name];return a?`background-image:url('assets/${a.atlas}.webp');background-position:${(a.index%4)*100/3}% ${Math.floor(a.index/4)*100/3}%;`:'';}
function sprite(name){const s=document.createElement('span');s.className='sprite';s.setAttribute('aria-hidden','true');s.style.cssText=artStyle(name);if(!ingredientArt[name]){s.textContent='+';s.style.cssText='display:grid;place-items:center;font-size:38px;color:#f7bbb8';}return s;}
function recipePool(){return data.items.filter(i=>i.sequence.length&&i.ingredients.length&&(settings.reference||i.source==='flushing'||i.source==='custom'));}
function fillRecipes(keep){const pool=recipePool();$('recipe').replaceChildren();for(const r of pool){const o=document.createElement('option');o.value=r.id;o.textContent=r.name+(r.source==='grand-blanc'?' · reference':'');$('recipe').append(o);}if(!pool.length){recipe=null;setFeedback('No active builds. Enable reference builds or add a recipe in admin.');return;}$('recipe').value=pool.some(r=>r.id===keep)?keep:pool[0].id;newTicket($('recipe').value);}
function newTicket(id){recipe=data.items.find(i=>i.id===id);if(!recipe)return;applied=[];prepared=false;completed=false;counted=false;attempts=0;mistakes=0;startTime=0;hintShown=false;$('recipe').value=id;$('ticket-name').textContent=recipe.name;$('ticket-number').textContent=String(ticketNumber).padStart(3,'0');$('ticket-origin').textContent=recipe.status;$('ticket-crust').textContent=recipe.crust;$('order-status').textContent=recipe.orderConfirmed?'Kitchen-confirmed sequence':'Exact practice sequence · kitchen confirmation needed';$('crust-choice').replaceChildren();for(const c of [...new Set([...crusts,recipe.crust])]){const o=document.createElement('option');o.value=c;o.textContent=c==='Not specified'?'No crust listed / store choice':c;$('crust-choice').append(o);}$('crust-choice').value='';$('prep').disabled=false;$('crust-choice').disabled=false;$('pizza').classList.remove('prepared');$('drop-cue').textContent='PREPARE DOUGH';$('layers').replaceChildren();$('next-ticket').hidden=true;$('game-time').textContent='0:00';renderRail();renderProgress();setFeedback('Select the crust from the ticket, then prepare dough.');}
function renderRail(){const expected=[...new Set(recipe.ingredients)],decoys=shuffle(allIngredients().filter(n=>!expected.includes(n))).slice(0,5),names=shuffle([...expected,...decoys]);$('rail-count').textContent=names.length+' bins';$('toppings').replaceChildren();for(const name of names){const b=document.createElement('button');b.className='topping';b.dataset.ingredient=name;b.setAttribute('aria-label','Add '+name);b.append(sprite(name));const text=document.createElement('span');text.textContent=name;b.append(text);attachDrag(b,name);$('toppings').append(b);}}
function renderProgress(){$('game-progress').textContent=`${applied.length} / ${recipe.sequence.length} ingredients`;$('game-bar').style.width=(applied.length/recipe.sequence.length*100)+'%';$('next-step').textContent=completed?'Ticket complete':!prepared?'Prepare your dough first':settings.guided||hintShown?'Next: '+recipe.sequence[applied.length]:'Recall the next ingredient from memory.';$('station-badge').textContent=completed?'Ready to serve':prepared?'Add toppings in '+'the exact saved order':'Choose crust to begin';$('applied-list').replaceChildren();for(const name of applied){const li=document.createElement('li');li.textContent=name;$('applied-list').append(li);}$('undo').disabled=!applied.length||counted;$('hint').disabled=!prepared||completed;}
$('prep').onclick=()=>{if(!recipe||prepared)return;if($('crust-choice').value!==recipe.crust){mistakes++;setFeedback('Check the crust on the ticket. '+(recipe.crust==='Not specified'?'This menu does not specify a crust flavor.':'Choose '+recipe.crust+'.'),true);return;}prepared=true;startTime=Date.now();$('pizza').classList.add('prepared');$('prep').disabled=true;$('crust-choice').disabled=true;renderProgress();setFeedback('Dough ready. Drag or tap the first ingredient.');};
function addIngredient(name){if(!unlocked()||active!=='game')return;if(!prepared){setFeedback('Prepare the dough before adding toppings.',true);return;}if(completed)return;attempts++;stats.buildAttempts++;const expected=recipe.sequence[applied.length];const correct=name===expected;if(!correct){mistakes++;save();setFeedback(recipe.ingredients.includes(name)?'That belongs on this pizza, but it is not the next practice step.':'That ingredient is not listed for this pizza.',true);return;}applied.push(name);stats.buildCorrect++;hintShown=false;paintPizza();if(applied.length===recipe.sequence.length){completed=true;if(!counted){stats.served++;counted=true;}const accuracy=Math.round(applied.length/(attempts+Math.max(0,mistakes-(attempts-applied.length)))*100);setFeedback(`Served! ${recipe.name} · ${accuracy}% first-pass accuracy${recipe.orderConfirmed?'':' · practice sequence'}.`);$('next-ticket').hidden=false;}else setFeedback(name+' added. Keep the build going.');renderProgress();updateStats();save();}
function paintPizza(){$('layers').replaceChildren();applied.forEach((name,layer)=>{if(!ingredientArt[name])return;const sauce=/sauce|gravy|dip/i.test(name)&&!/(drizzle|ranch)/i.test(name),cheese=/cheese|mozzarella|cheddar/i.test(name);const n=sauce?1:cheese?8:9;for(let i=0;i<n;i++){const s=document.createElement('span');s.className='placed'+(sauce?' sauce':cheese?' cheese':'');s.style.cssText=artStyle(name);s.style.zIndex=layer+1;if(!sauce){const angle=(i*2.399963+layer*.7),radius=10+Math.sqrt((i+1)/n)*28;s.style.left=(50+Math.cos(angle)*radius)+'%';s.style.top=(50+Math.sin(angle)*radius)+'%';s.style.width=(cheese?38:20)+'%';s.style.transform=`translate(-50%,-50%) rotate(${(i*41+layer*13)%360}deg)`;}$('layers').append(s);}});}
function attachDrag(button,name){let drag=null,skipClick=false;button.draggable=true;button.addEventListener('dragstart',e=>{drag?.ghost?.remove();drag=null;skipClick=true;e.dataTransfer.setData('text/plain',name);e.dataTransfer.effectAllowed='copy';});button.addEventListener('dragend',()=>{$('pizza').classList.remove('over');setTimeout(()=>skipClick=false,0);});button.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false,ghost:null};button.setPointerCapture(e.pointerId);});button.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8&&!drag.moved){drag.moved=true;drag.ghost=document.createElement('div');drag.ghost.className='drag-ghost';drag.ghost.append(sprite(name));document.body.append(drag.ghost);}if(drag.moved){drag.ghost.style.left=(e.clientX-50)+'px';drag.ghost.style.top=(e.clientY-50)+'px';$('pizza').classList.toggle('over',overPizza(e.clientX,e.clientY));if(e.clientY<65)window.scrollBy(0,-12);if(e.clientY>innerHeight-65)window.scrollBy(0,12);}});button.addEventListener('pointerup',e=>{if(!drag)return;skipClick=drag.moved;if(drag.moved){if(overPizza(e.clientX,e.clientY))addIngredient(name);else setFeedback('Drop the ingredient onto the pizza, or tap its bin.');}drag.ghost?.remove();drag=null;$('pizza').classList.remove('over');});for(const type of ['pointercancel','lostpointercapture'])button.addEventListener(type,()=>{drag?.ghost?.remove();drag=null;$('pizza').classList.remove('over');});button.addEventListener('click',()=>{if(skipClick){skipClick=false;return;}addIngredient(name);});}
function overPizza(x,y){const r=$('pizza').getBoundingClientRect();return Math.hypot(x-(r.left+r.width/2),y-(r.top+r.height/2))<=r.width*.45;}
$('hint').onclick=()=>{hintShown=true;renderProgress();};$('undo').onclick=()=>{if(!applied.length||counted)return;applied.pop();paintPizza();renderProgress();setFeedback('Last ingredient removed.');};$('restart').onclick=()=>newTicket(recipe.id);$('recipe').onchange=e=>newTicket(e.target.value);
function randomTicket(){const pool=recipePool().filter(r=>r.id!==recipe?.id);ticketNumber++;newTicket((shuffle(pool)[0]||recipePool()[0]).id);}$('random-ticket').onclick=randomTicket;$('next-ticket').onclick=randomTicket;
setInterval(()=>{if(startTime&&!completed&&unlocked()&&active==='game'){const seconds=Math.floor((Date.now()-startTime)/1000);$('game-time').textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');}},1000);
function updateStats(){$('mastery').textContent=stats.served+' pizza'+(stats.served===1?'':'s')+' served';$('stats-detail').textContent=`${stats.served} pizzas served · ${stats.quizTests} tests completed · ${stats.quizCorrect}/${stats.quizAnswers} quiz answers correct · best test ${stats.best}%.`;}
function sourceUrl(item){return data.meta.sources.find(s=>s.id===(item.sourceId||item.source))?.url||data.meta.sources[0].url;}
function renderStudy(){const query=$('search').value.trim().toLowerCase(),category=$('category').value,scope=$('study-scope').value;const items=data.items.filter(i=>(category==='all'||i.category===category)&&(scope==='all'||i.source===scope)&&[i.name,i.category,i.description,i.ingredients.join(' ')].join(' ').toLowerCase().includes(query));$('menu-count').textContent=`${items.length} of ${data.items.length} researched entries · Reference-only items need local confirmation.`;$('menu-grid').replaceChildren();if(!items.length){$('menu-grid').innerHTML='<p class="empty">No matching items. Try another category or search.</p>';return;}for(const i of items){const card=document.createElement('article');card.className='menu-item';card.innerHTML=`<span class="tag ${i.source==='grand-blanc'?'reference':''}">${esc(i.status)}</span><h3>${esc(i.name)}</h3><span class="eyebrow">${esc(i.category)}</span><p>${esc(i.description)}</p>`;if(i.ingredients.length){const tags=document.createElement('div');tags.className='ingredient-tags';for(const n of (i.publishedIngredients||i.ingredients)){const t=document.createElement('span');t.textContent=n;tags.append(t);}card.append(tags);}if(i.crust!=='Not specified'){const p=document.createElement('p');p.textContent='Crust: '+i.crust;card.append(p);}if(i.sequence.length){const b=document.createElement('button');b.textContent='Practice this pizza';b.onclick=()=>{if(!settings.reference&&i.source==='grand-blanc'){showView('game');setFeedback('This build is a Grand Blanc reference. Enable reference builds in admin to practice it.');return;}showView('game');newTicket(i.id);window.scrollTo({top:0,behavior:'smooth'});};card.append(b);}const a=document.createElement('a');a.className='source-link';a.href=sourceUrl(i);a.textContent='Menu source';a.target='_blank';a.rel='noopener';card.append(a);$('menu-grid').append(card);}}
function fillStudyCategories(){const current=$('category').value;$('category').innerHTML='<option value="all">All categories</option>';for(const c of [...new Set(data.items.map(i=>i.category))].sort()){const o=document.createElement('option');o.value=c;o.textContent=c;$('category').append(o);}$('category').value=[...$('category').options].some(o=>o.value===current)?current:'all';}
for(const id of ['search','category','study-scope'])$(id).addEventListener(id==='search'?'input':'change',renderStudy);
function makeQuestion(item,index){const menuIngredients=item.publishedIngredients||item.ingredients;const categories=[...new Set(data.items.map(i=>i.category))];if(menuIngredients.length&&index%3!==0){const answer=shuffle(menuIngredients)[0],wrong=shuffle(allIngredients().filter(n=>!menuIngredients.includes(n))).slice(0,3);return {item,prompt:`Which ingredient is listed for ${item.name}?`,answer,options:shuffle([answer,...wrong]),explain:'Listed ingredients: '+menuIngredients.join(', ')+'.'};}if(item.crust!=='Not specified'){const answer=item.crust;return {item,prompt:`Which crust is listed for ${item.name}?`,answer,options:shuffle([answer,...shuffle(crusts.filter(c=>c!==answer&&c!=='Not specified')).slice(0,3)]),explain:'The published crust is '+answer+'.'};}const answer=item.category;return {item,prompt:`Where does ${item.name} belong on the menu?`,answer,options:shuffle([answer,...shuffle(categories.filter(c=>c!==answer)).slice(0,3)]),explain:item.description};}
function startQuiz(){let pool=data.items.filter(i=>$('quiz-scope').value==='all'||i.source==='flushing');pool=shuffle(pool);const count=$('quiz-length').value==='all'?pool.length:Math.min(+$('quiz-length').value,pool.length);quiz={questions:pool.slice(0,count).map(makeQuestion),index:0,answers:[],answered:false};$('quiz-results').hidden=true;renderQuestion();}
function renderQuestion(){const q=quiz.questions[quiz.index];if(!q){finishQuiz();return;}quiz.answered=false;$('quiz-count').textContent=`Question ${quiz.index+1} / ${quiz.questions.length}`;$('quiz-question').textContent=q.prompt;$('quiz-origin').textContent=q.item.status;$('quiz-feedback').textContent='';$('quiz-next').hidden=true;$('quiz-options').replaceChildren();for(const text of q.options){const b=document.createElement('button');b.textContent=text;b.onclick=()=>answerQuestion(text);$('quiz-options').append(b);}}
function answerQuestion(answer){if(quiz.answered||!unlocked())return;const q=quiz.questions[quiz.index];if(!q)return;quiz.answered=true;const correct=answer===q.answer;quiz.answers.push({name:q.item.name,prompt:q.prompt,answer,correct,expected:q.answer});stats.quizAnswers++;if(correct)stats.quizCorrect++;for(const b of $('quiz-options').children){b.disabled=true;if(b.textContent===q.answer)b.classList.add('correct');else if(b.textContent===answer)b.classList.add('wrong');}$('quiz-feedback').textContent=(correct?'Correct. ':'Answer: '+q.answer+'. ')+q.explain;$('quiz-next').hidden=false;$('quiz-next').textContent=quiz.index===quiz.questions.length-1?'See results':'Next question';save();}
function finishQuiz(){if(!quiz.questions.length)return;const correct=quiz.answers.filter(a=>a.correct).length,score=Math.round(correct/quiz.questions.length*100);stats.quizTests++;stats.best=Math.max(stats.best,score);updateStats();save();$('quiz-count').textContent='Test complete';$('quiz-question').textContent=`${score}% · ${correct} / ${quiz.questions.length} correct`;$('quiz-origin').textContent='Review the misses, then use the menu guide to study.';$('quiz-options').replaceChildren();$('quiz-feedback').textContent='';$('quiz-next').hidden=true;$('quiz-results').hidden=false;$('quiz-results').replaceChildren();for(const a of quiz.answers.filter(a=>!a.correct)){const row=document.createElement('div');row.className='review-row';row.innerHTML=`<strong>${esc(a.name)}</strong><p>${esc(a.prompt)}</p><span>Correct answer: ${esc(a.expected)}</span>`;$('quiz-results').append(row);}if(correct===quiz.questions.length)$('quiz-results').textContent='Perfect test. Nicely done.';}
$('quiz-start').onclick=startQuiz;$('quiz-next').onclick=()=>{if(!quiz.answered)return;quiz.index++;renderQuestion();};
function validateItems(items){if(!Array.isArray(items)||!items.length||items.length>300)throw Error('Menu must contain 1–300 items.');const ids=new Set();return items.map((i,n)=>{if(!i||typeof i.name!=='string'||!i.name.trim()||i.name.length>150)throw Error('Invalid item name at row '+(n+1));const id=String(i.id||'custom-'+n);if(!/^[a-zA-Z0-9_-]{1,120}$/.test(id)||ids.has(id))throw Error('Invalid or duplicate item ID.');ids.add(id);for(const key of ['ingredients','sequence'])if(!Array.isArray(i[key])||i[key].length>50||i[key].some(s=>typeof s!=='string'||!s.trim()||s.length>100))throw Error('Invalid '+key+' for '+i.name);if([...i.sequence].sort().join('\n')!==[...i.ingredients].sort().join('\n'))throw Error('Sequence must contain each ingredient exactly once, including any repeated ingredient.');if(i.sequence.length&&(!i.ingredients.some(x=>/sauce|gravy|cream cheese dip/i.test(x))||!i.ingredients.some(x=>/cheese|mozzarella|cheddar|cotija/i.test(x)&&!(/cream cheese dip/i.test(x)))))throw Error('Every pizza build requires both a sauce and a cheese step.');if(typeof i.category!=='string'||!i.category.trim()||i.category.length>100)throw Error('Invalid category.');if(typeof i.crust!=='string'||i.crust.length>100)throw Error('Invalid crust.');const source=['flushing','grand-blanc','custom'].includes(i.source)?i.source:'custom';return {...i,id,name:i.name.trim(),category:i.category.trim(),description:String(i.description||'').slice(0,2000),ingredients:i.ingredients.map(x=>x.trim()),sequence:i.sequence.map(x=>x.trim()),crust:i.crust.trim()||'Not specified',source,status:source==='custom'?'Edited on this device':source==='flushing'?'Flushing listing':'Grand Blanc reference',orderConfirmed:i.orderConfirmed===true};});}
function fillEditor(keep){$('edit-item').replaceChildren();for(const i of data.items){const o=document.createElement('option');o.value=i.id;o.textContent=i.name;$('edit-item').append(o);}$('edit-item').value=data.items.some(i=>i.id===keep)?keep:data.items[0].id;loadEditor();}
function loadEditor(){const i=data.items.find(i=>i.id===$('edit-item').value);if(!i)return;$('edit-name').value=i.name;$('edit-category').value=i.category;$('edit-crust').value=i.crust;$('edit-description').value=i.description;$('edit-ingredients').value=i.ingredients.join('\n');$('edit-sequence').value=i.sequence.join('\n');$('edit-confirmed').checked=i.orderConfirmed;$('edit-feedback').textContent='';}
$('edit-item').onchange=loadEditor;
$('save-item').onclick=()=>{if(!admin)return;const old=data.items.find(i=>i.id===$('edit-item').value),list=s=>s.split('\n').map(x=>x.trim()).filter(Boolean);try{const item=validateItems([{...old,name:$('edit-name').value,category:$('edit-category').value,crust:$('edit-crust').value,description:$('edit-description').value,ingredients:list($('edit-ingredients').value),sequence:list($('edit-sequence').value),orderConfirmed:$('edit-confirmed').checked,publishedIngredients:undefined,source:'custom'}])[0];data.items[data.items.findIndex(i=>i.id===old.id)]=item;save();fillEditor(item.id);fillStudyCategories();renderStudy();fillRecipes(recipe?.id);$('edit-feedback').textContent='Saved. Practice sequence and quizzes now use your edited recipe.';}catch(e){$('edit-feedback').textContent=e.message;}};
for(const [id,key]of [['setting-guided','guided'],['setting-reference','reference']])$(id).onchange=e=>{if(!admin)return;settings[key]=e.target.checked;save();if(key==='reference')fillRecipes(recipe?.id);else newTicket(recipe.id);};
$('new-item').onclick=()=>{if(!admin)return;const item={id:'custom-'+Date.now(),name:'New menu item',category:'Pizza',description:'Add verified menu details here.',ingredients:[],sequence:[],crust:'Not specified',source:'custom',status:'Edited on this device',orderConfirmed:false};data.items.push(item);save();fillEditor(item.id);fillStudyCategories();renderStudy();};
$('export').onclick=()=>{if(!admin)return;const blob=new Blob([JSON.stringify({...data,exported:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='MATTBEAR-Enzos-Trainer-Menu.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('admin-feedback').textContent='Export created. Keep the JSON to restore your edited menu.';};
$('import').onchange=async e=>{if(!admin)return;const file=e.target.files[0];if(!file)return;try{if(file.size>1024*1024)throw Error('Choose a menu JSON smaller than 1 MB.');const parsed=JSON.parse(await file.text()),items=validateItems(parsed.items);data.items=items;save();fillEditor();fillStudyCategories();renderStudy();fillRecipes();$('admin-feedback').textContent='Imported '+items.length+' items. Sources stay tied to the researched menu.';}catch(err){$('admin-feedback').textContent='Import failed: '+err.message;}e.target.value='';};
let restoreArmed=false,resetArmed=false;
$('reset-menu').onclick=()=>{if(!admin)return;if(!restoreArmed){restoreArmed=true;$('reset-menu').textContent='Click again to restore menu';setTimeout(()=>{restoreArmed=false;$('reset-menu').textContent='Restore researched menu';},5000);return;}data=structuredClone(original);save();fillEditor();fillStudyCategories();renderStudy();fillRecipes();restoreArmed=false;$('reset-menu').textContent='Restore researched menu';$('admin-feedback').textContent='Researched menu restored. Custom edits removed on this device.';};
$('reset-progress').onclick=()=>{if(!admin)return;if(!resetArmed){resetArmed=true;$('reset-progress').textContent='Click again to clear scores';setTimeout(()=>{resetArmed=false;$('reset-progress').textContent='Reset practice scores';},5000);return;}stats={served:0,buildAttempts:0,buildCorrect:0,quizTests:0,quizAnswers:0,quizCorrect:0,best:0};quiz={questions:[],index:0,answers:[],answered:false};updateStats();save();resetArmed=false;$('reset-progress').textContent='Reset practice scores';$('admin-feedback').textContent='Practice scores cleared.';};
$('admin-open').onclick=()=>{if(admin){showView('admin-panel');updateStats();return;}$('admin-code').value='';$('admin-message').textContent='';$('admin-dialog').showModal();};
$('admin-form').onsubmit=async e=>{e.preventDefault();try{if(await validCode($('admin-code').value)){admin=true;$('admin-dialog').close();$('admin-code').value='';fillEditor(recipe?.id);for(const [id,key]of [['setting-guided','guided'],['setting-reference','reference']])$(id).checked=settings[key];updateStats();showView('admin-panel');}else $('admin-message').textContent='Incorrect four-digit code.';}catch{$('admin-message').textContent='Code check unavailable. Use the hosted HTTPS page.';}};
$('admin-cancel').onclick=()=>$('admin-dialog').close();$('admin-close').onclick=()=>showView('game');
$('unlock-form').onsubmit=async e=>{e.preventDefault();if(!data){$('unlock-message').textContent='Menu is still loading. Try again in a moment.';return;}try{if(await validCode($('unlock-code').value)){$('splash').hidden=true;$('app').hidden=false;$('unlock-code').value='';showView('game');}else $('unlock-message').textContent='Incorrect code. Enter four digits.';}catch{$('unlock-message').textContent='Code check unavailable. Open this trainer through HTTPS.';}};
$('lock').onclick=()=>{admin=false;$('app').hidden=true;$('splash').hidden=false;$('unlock-message').textContent='';$('unlock-code').value='';$('unlock-code').focus();prepared=false;if(recipe)newTicket(recipe.id);};
for(const b of document.querySelectorAll('.tabs button'))b.onclick=()=>showView(b.dataset.tab);
$('source-open').onclick=()=>$('sources').showModal();$('sources-close').onclick=()=>$('sources').close();
async function init(){try{const r=await fetch('menu.json');if(!r.ok)throw Error('Menu unavailable');original=await r.json();original.items=validateItems(original.items);data=structuredClone(original);const saved=readStore();if(saved.items){try{data.items=validateItems(saved.items.map(i=>{const current=original.items.find(x=>x.id===i.id);if(current&&i.source!=='custom'&&(i.buildVersion||0)<2)return structuredClone(current);if(i.source==='custom'&&Array.isArray(i.sequence)&&i.sequence.length){const missing=[];if(!i.ingredients.some(x=>/sauce|gravy|cream cheese dip/i.test(x)))missing.push('Base sauce (confirm with kitchen)');if(!i.ingredients.some(x=>/cheese|mozzarella|cheddar|cotija/i.test(x)&&!(/cream cheese dip/i.test(x))))missing.push('Base cheese (confirm with kitchen)');if(missing.length)return {...i,ingredients:[...missing,...i.ingredients],sequence:[...missing,...i.sequence],orderConfirmed:false};}return i;}));}catch{}}
 if(saved.settings)for(const k of Object.keys(settings))if(typeof saved.settings[k]==='boolean')settings[k]=saved.settings[k];settings.strict=true;if(saved.stats)for(const k of Object.keys(stats))if(Number.isFinite(saved.stats[k])&&saved.stats[k]>=0)stats[k]=saved.stats[k];fillRecipes();fillStudyCategories();renderStudy();updateStats();for(const source of data.meta.sources){const a=document.createElement('a');a.href=source.url;a.textContent=source.name;a.target='_blank';a.rel='noopener';$('source-links').append(a);}}catch(e){console.error(e);$('unlock-message').textContent='Menu could not load. Refresh with a connection to try again.';}}
init();

$('pizza').addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('text/plain')){e.preventDefault();e.dataTransfer.dropEffect='copy';$('pizza').classList.toggle('over',overPizza(e.clientX,e.clientY));}});
$('pizza').addEventListener('dragleave',()=>{$('pizza').classList.remove('over');});
$('pizza').addEventListener('drop',e=>{e.preventDefault();$('pizza').classList.remove('over');const name=e.dataTransfer.getData('text/plain');if(allIngredients().includes(name)&&overPizza(e.clientX,e.clientY))addIngredient(name);});
