'use strict';
const GROOVE_KEY='mattbear-acoustic-groove-v1',svgNS='http://www.w3.org/2000/svg';
let take=[],hitSerial=0,transport={running:false,mode:'stopped',origin:0,nextClick:0,seen:new Set()},clockTimer,transportRequest=0,clickVoices=new Set(),visualTimers=new Set(),effects=[],fxFrame=0,lastBeat=-1;
const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
function bpm(){return Math.max(40,Math.min(240,Number($('bpm').value)||120));}function beatSeconds(){return 60/bpm();}function totalBeats(){return Number($('loop-bars').value)*4;}function grid(){return Number($('quantize').value);}
function snapBeat(beat,step=grid(),length=totalBeats()){const snapped=step?Math.round(beat/step)*step:beat;return ((snapped%length)+length)%length;}
function saveGroove(){try{const controls={};for(const id of ['bpm','loop-bars','quantize','metro','metro-level','fx-style','fx-color','fx-intensity','fx-speed','fx-tail','fx-clock'])controls[id]=$(id).type==='checkbox'?$(id).checked:$(id).value;localStorage.setItem(GROOVE_KEY,JSON.stringify({controls,take}));}catch{$('transport-status').textContent='Browser storage unavailable. This loop stays available until you close the page.';}}
try{const saved=JSON.parse(localStorage.getItem(GROOVE_KEY));if(saved?.controls){for(const id of ['bpm','loop-bars','quantize','metro','metro-level','fx-style','fx-color','fx-intensity','fx-speed','fx-tail','fx-clock']){const input=$(id),v=saved.controls[id];if(input.type==='checkbox'){if(typeof v==='boolean')input.checked=v;}else if(input.tagName==='SELECT'){if([...input.options].some(o=>o.value===String(v)))input.value=v;}else if(input.type==='color'){if(/^#[\da-f]{6}$/i.test(v))input.value=v;}else if(Number.isFinite(+v))input.value=Math.max(+input.min,Math.min(+input.max,+v));}}if(Array.isArray(saved?.take))take=saved.take.slice(0,2048).filter(e=>e&&pieces.some(p=>p.id===e.id)&&Number.isFinite(e.beat)&&e.beat>=0&&e.beat<totalBeats()&&Number.isFinite(e.v)&&e.v>=1&&e.v<=127&&['kick','snare','high','mid','floor','closed','open','pedal','crash','crash2','ride','bell','splash','china','cowbell'].includes(e.actual)).map(e=>({...e,uid:++hitSerial,bell:e.bell===true}));}catch{}
if(reduced){$('fx-style').value='off';$('fx-clock').checked=false;}
function svgEl(type,attributes){const e=document.createElementNS(svgNS,type);for(const [key,value]of Object.entries(attributes))e.setAttribute(key,value);return e;}
function renderTake(){const canvas=$('take-map');canvas.replaceChildren();const length=totalBeats();for(let b=0;b<=length;b++){const line=svgEl('line',{x1:10+b/length*700,x2:10+b/length*700,y1:8,y2:92,stroke:b%4===0?'#73828e':'#28353e','stroke-width':b%4===0?1.5:1});canvas.append(line);}const ids=[...new Set(take.map(e=>e.id))];for(const e of take){const row=ids.indexOf(e.id);const dot=svgEl('circle',{cx:10+e.beat/length*700,cy:18+row/Math.max(1,ids.length)*68,r:2+e.v/127*3,fill:$('fx-color').value});const title=svgEl('title',{});title.textContent=(pieces.find(p=>p.id===e.id)?.name||e.id)+' · beat '+(e.beat+1).toFixed(2)+' · velocity '+e.v;dot.append(title);canvas.append(dot);}canvas.append(svgEl('line',{id:'take-playhead',x1:10,x2:10,y1:0,y2:100,stroke:'#e8f7ff','stroke-width':2}));$('take-count').textContent=take.length+' recorded hit'+(take.length===1?'':'s');}
function syncTakePieces(){take=take.filter(e=>pieces.some(p=>p.id===e.id));saveGroove();renderTake();}
function recordHit(hit,time){if(!transport.running)return;advanceRecording(time);if(!['recording','overdub'].includes(transport.mode)||time<transport.origin)return;if(take.length>=2048)return;const raw=(time-transport.origin)/beatSeconds(),beat=snapBeat(raw),cycle=Math.floor(raw/totalBeats());const existing=take.find(e=>e.id===hit.id&&e.actual===hit.actual&&Math.abs(e.beat-beat)<.0001);const event={...hit,beat,uid:existing?.uid||++hitSerial};if(existing)Object.assign(existing,event);else take.push(event);transport.seen.add(cycle+':'+event.uid);take.sort((a,b)=>a.beat-b.beat||a.uid-b.uid);renderTake();if(transport.mode==='overdub')saveGroove();}
function transportControls(){for(const id of ['bpm','loop-bars','quantize'])$(id).disabled=transport.running;$('record-loop').disabled=transport.running;$('record-loop').classList.toggle('recording',['count-in','recording'].includes(transport.mode));$('play-loop').disabled=transport.running;$('overdub').disabled=!transport.running||['count-in','recording'].includes(transport.mode);$('overdub').setAttribute('aria-pressed',transport.mode==='overdub');$('overdub').textContent='Overdub: '+(transport.mode==='overdub'?'on':'off');}
function advanceRecording(now){if(transport.mode==='count-in'&&now>=transport.origin){transport.mode='recording';$('transport-status').textContent='Recording. Play your kit now; each hit is captured on the selected grid.';transportControls();}if(transport.mode==='recording'&&now>=transport.origin+totalBeats()*beatSeconds()){transport.mode='playing';saveGroove();$('transport-status').textContent='Loop recorded. Playback is clocked; turn on Overdub to add more hits.';transportControls();}}
function clickAt(time,accent){if(!$('metro').checked||+$('metro-level').value===0)return;const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=accent?1400:950;gain.gain.setValueAtTime(+$('metro-level').value,time);gain.gain.exponentialRampToValueAtTime(.0001,time+.04);osc.connect(gain).connect(master);clickVoices.add(osc);osc.onended=()=>{clickVoices.delete(osc);osc.disconnect();gain.disconnect();};osc.start(time);osc.stop(time+.045);}
function scheduleClock(){if(!transport.running||!ctx)return;const now=ctx.currentTime,horizon=now+.1;advanceRecording(now);if(transport.nextClick<now-.1)transport.nextClick=transport.origin+Math.ceil((now-transport.origin)/beatSeconds())*beatSeconds();while(transport.nextClick<horizon){const beat=Math.round((transport.nextClick-transport.origin)/beatSeconds());clickAt(transport.nextClick,((beat%4)+4)%4===0);transport.nextClick+=beatSeconds();}if(!take.length)return;const duration=totalBeats()*beatSeconds(),first=Math.max(0,Math.floor((now-transport.origin)/duration));for(let cycle=first;cycle<=first+1;cycle++){if(['count-in','recording'].includes(transport.mode)&&cycle===0)continue;for(const e of take){const at=transport.origin+cycle*duration+e.beat*beatSeconds(),key=cycle+':'+e.uid;if(at>=now-.015&&at<horizon&&!transport.seen.has(key)){transport.seen.add(key);play(e.id,e.v,e.bell,{at:Math.max(now,at),clock:true,actual:e.actual});}}}if(transport.seen.size>4096)transport.seen=new Set([...transport.seen].filter(key=>+key.split(':')[0]>=first-1));}
async function startTransport(record=false){if(transport.running)return;const request=++transportRequest;if(!await enable())return;if(request!==transportRequest||transport.running)return;if(moving)$('mode').click();const start=ctx.currentTime+.08;transport={running:true,mode:record?'count-in':'playing',origin:start+(record?4*beatSeconds():0),nextClick:start,seen:new Set()};if(record){take=[];renderTake();}$('transport-status').textContent=record?'Count in: four beats. Record begins on the next downbeat.':'Clock running. Your loop repeats at '+bpm()+' BPM.';transportControls();clockTimer=setInterval(scheduleClock,25);scheduleClock();ensureFrame();}
function stopTransport(){transportRequest++;if(!transport.running)return;transport.running=false;transport.mode='stopped';clearInterval(clockTimer);stopSet(voices);for(const osc of clickVoices){try{osc.stop();}catch{}}clickVoices.clear();for(const timer of visualTimers)clearTimeout(timer);visualTimers.clear();stage.classList.remove('clock-pulse');saveGroove();transportControls();$('clock-readout').textContent='Stopped · '+bpm()+' BPM';$('transport-status').textContent='Stopped. '+take.length+' hits saved. Play resumes from the first beat.';document.querySelectorAll('.beat-lights i').forEach(e=>e.classList.remove('active'));lastBeat=-1;}
$('record-loop').onclick=()=>startTransport(true);$('play-loop').onclick=()=>startTransport(false);$('stop-loop').onclick=stopTransport;$('clear-loop').onclick=()=>{stopTransport();take=[];renderTake();saveGroove();$('transport-status').textContent='Loop cleared. Record new loop starts after four count-in beats.';};$('overdub').onclick=()=>{if(!transport.running||['count-in','recording'].includes(transport.mode))return;transport.mode=transport.mode==='overdub'?'playing':'overdub';transportControls();$('transport-status').textContent=transport.mode==='overdub'?'Overdub on. Play to add snapped hits while your loop keeps running.':'Overdub off. Loop playing.';};
for(const id of ['bpm','loop-bars','quantize','metro','metro-level'])$(id).onchange=()=>{if(id==='bpm')$('bpm').value=bpm();if(id==='loop-bars'){take=take.filter(e=>e.beat<totalBeats());renderTake();$('transport-status').textContent='Loop length changed. Hits beyond the new end are removed.';}saveGroove();if(!transport.running)$('clock-readout').textContent='Stopped · '+bpm()+' BPM';};
const fxCanvas=$('kit-fx'),fxCtx=fxCanvas.getContext('2d');let fxW=0,fxH=0;
function resizeFx(){fxW=stage.clientWidth;fxH=stage.clientHeight;const scale=Math.min(2,window.devicePixelRatio||1);fxCanvas.width=Math.max(1,fxW*scale);fxCanvas.height=Math.max(1,fxH*scale);fxCtx?.setTransform(scale,0,0,scale,0,0);}
function applyFx(){stage.style.setProperty('--fx-color',$('fx-color').value);stage.style.setProperty('--hit-brightness',String(1+Number($('fx-intensity').value)*.6));if($('fx-style').value==='off'||+$('fx-intensity').value===0){effects=[];fxCtx?.clearRect(0,0,fxW,fxH);}renderTake();saveGroove();}
for(const id of ['fx-style','fx-color','fx-intensity','fx-speed','fx-tail','fx-clock'])$(id).oninput=applyFx;
function scheduleVisual(id,v,at){const delay=Math.max(0,(at-ctx.currentTime)*1000);if(delay<4){triggerVisual(id,v);return;}const timer=setTimeout(()=>{visualTimers.delete(timer);triggerVisual(id,v);},delay);visualTimers.add(timer);}
function triggerVisual(id,v){const p=pieces.find(p=>p.id===id);if(!p)return;if($('fx-style').value==='off'||+$('fx-intensity').value===0)return;flash(id);if(fxCtx){effects.push({x:p.x/100*fxW,y:p.y/100*fxH,start:performance.now(),v:v/127,size:p.size/100*fxW,seed:Math.random()*6.28});if(effects.length>64)effects.shift();ensureFrame();}}
function ensureFrame(){if(!fxFrame)fxFrame=requestAnimationFrame(visualFrame);}
function visualFrame(now){fxFrame=0;if(fxCtx){fxCtx.clearRect(0,0,fxW,fxH);const life=+$('fx-tail').value*1000/+$('fx-speed').value,intensity=+$('fx-intensity').value,style=$('fx-style').value;effects=effects.filter(e=>now-e.start<life);fxCtx.strokeStyle=fxCtx.fillStyle=$('fx-color').value;for(const e of effects){const t=(now-e.start)/life,alpha=(1-t)*intensity;fxCtx.globalAlpha=alpha;const radius=e.size*(.25+t*.7)*(.5+e.v*.5);if(style==='rings'||style==='both'){fxCtx.lineWidth=1+e.v*3;fxCtx.beginPath();fxCtx.arc(e.x,e.y,radius,0,Math.PI*2);fxCtx.stroke();}if(style==='sparks'||style==='both'){const n=8+Math.round(12*intensity);for(let i=0;i<n;i++){const angle=i/n*Math.PI*2+e.seed,x=e.x+Math.cos(angle)*radius,y=e.y+Math.sin(angle)*radius;fxCtx.beginPath();fxCtx.arc(x,y,Math.max(.5,(1-t)*(1+e.v*3)),0,Math.PI*2);fxCtx.fill();}}}fxCtx.globalAlpha=1;}
if(transport.running&&ctx){const raw=(ctx.currentTime-transport.origin)/beatSeconds(),beat=Math.floor(raw),pos=((raw%totalBeats())+totalBeats())%totalBeats();if(raw<0)$('clock-readout').textContent='Count in · '+Math.min(4,Math.max(1,Math.floor(raw+4)+1))+' / 4';else $('clock-readout').textContent=(transport.mode==='recording'?'REC · ':transport.mode==='overdub'?'DUB · ':'PLAY · ')+('Bar '+(Math.floor(pos/4)+1)+' / '+$('loop-bars').value+' · beat '+(Math.floor(pos)%4+1));if(beat!==lastBeat){lastBeat=beat;document.querySelectorAll('.beat-lights i').forEach((e,i)=>e.classList.toggle('active',i===((beat%4)+4)%4));stage.classList.toggle('clock-pulse',$('fx-clock').checked&&+$('fx-intensity').value>0);}else if(raw-beat>.2)stage.classList.remove('clock-pulse');const playhead=$('take-playhead');if(playhead){playhead.setAttribute('x1',10+pos/totalBeats()*700);playhead.setAttribute('x2',10+pos/totalBeats()*700);}}
if(effects.length||transport.running)ensureFrame();}
window.addEventListener('resize',resizeFx);if(typeof ResizeObserver!=='undefined')new ResizeObserver(resizeFx).observe(stage);document.addEventListener('visibilitychange',()=>{if(document.hidden&&transport.running){stopTransport();$('transport-status').textContent='Clock stopped while this tab was hidden. Your loop is saved; press Play to restart.';}});window.addEventListener('pagehide',stopTransport);
resizeFx();applyFx();transportControls();renderTake();$('clock-readout').textContent='Stopped · '+bpm()+' BPM';
