'use strict';
const $=id=>document.getElementById(id), stage=$('stage'), status=$('status');
const defaults=[
 ['kick','Kick · 18″',' ',52,55,22,'kick',36,'18×18″ acoustic bass drum.',1,0],
 ['snare','Snare · 14″','s',37,67,18,'drum',38,'14×5″ birch/mahogany stave snare.',.72,0],
 ['high','High tom · 12″','d',39,39,16,'drum',50,'Recorded 12×7″ rack tom.',.9,0],
 ['mid','Mid tom','f',59,39,17,'drum',47,'12″ rack-tom recording tuned down 3 semitones.',.9,-3],
 ['floor','Floor tom · 14″','g',76,68,21,'drum',43,'Recorded 14×14″ floor tom.',.9,0],
 ['closed','Hi-hat · 14″','a',17,59,18,'cymbal',42,'Stagg 14″ hi-hat. Shift opens it; X closes it.',.35,0],
 ['crash','Crash · 18″','q',20,25,23,'cymbal',49,'Paiste 18″ Innovations medium crash.',.45,0],
 ['crash2','Crash · 16″','e',78,25,21,'cymbal',57,'Stagg 16″ SH crash.',.4,0],
 ['ride','Ride · 20″','r',81,47,24,'cymbal',51,'20″ ride bow; tap its BELL zone or press T for the bell.',.45,0],
 ['splash','Splash · 8″','w',49,18,11,'cymbal',55,'Paiste 8″ PST5 splash.',.45,0],
 ['china','China · 20″','c',88,81,17,'cymbal',52,'Masterworks 20″ Custom china.',.4,0],
 ['cowbell','Cowbell','v',63,20,9,'cowbell',56,'Recorded acoustic cowbell.',.5,0]
].map(([id,name,key,x,y,size,type,note,desc,level,tune])=>({id,name,key,x,y,size,type,note,desc,level,tune}));
let pieces=structuredClone(defaults), moving=false,selected='snare',ctx,master,limiter,loading,buffers={},manifest,round={},voices=new Set(),hatVoices=new Set(),cymVoices=new Set(),shift=false,ready=false;
try{const saved=JSON.parse(localStorage.getItem('mattbear-acoustic-kit-v1'));if(Array.isArray(saved))for(const d of pieces){const s=saved.find(x=>x.id===d.id);if(s)for(const [key,min,max] of [['x',10,90],['y',12,83],['size',8,24],['level',0,1.5],['tune',-6,6]])if(Number.isFinite(s[key]))d[key]=Math.max(min,Math.min(max,s[key]));}}catch{}
function save(){try{localStorage.setItem('mattbear-acoustic-kit-v1',JSON.stringify(pieces));}catch{status.textContent='Layout works here, but browser storage is unavailable.';}}
function position(p){const b=$('pad-'+p.id);b.style.left=p.x+'%';b.style.top=p.y+'%';b.style.width=p.size+'%';}
function select(id){selected=id;const p=pieces.find(p=>p.id===id);$('piece').value=id;$('description').textContent=p.desc;for(const [a,b]of [['posx','x'],['posy','y'],['size','size'],['level','level'],['tune','tune']])$(a).value=p[b];$('tunevalue').textContent=p.tune;document.querySelectorAll('.drum').forEach(b=>b.classList.toggle('selected',b.id==='pad-'+id));}
for(const p of pieces){const b=document.createElement('button');b.id='pad-'+p.id;b.className='drum '+p.type;b.setAttribute('aria-label',p.name+'; key '+(p.key===' '?'Space':p.key.toUpperCase()));b.innerHTML=`<span>${p.name}</span><small>${p.key===' '?'SPACE':p.key.toUpperCase()}</small>`;if(p.id==='ride')b.innerHTML+='<span class="bell-zone" data-bell="true">BELL</span>';stage.append(b);position(p);const opt=document.createElement('option');opt.value=p.id;opt.textContent=p.name;$('piece').append(opt);
 let drag;
 b.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;e.preventDefault();select(p.id);if(moving){const r=stage.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:p.x,py:p.y,w:r.width,h:r.height};b.setPointerCapture(e.pointerId);}else{const v=e.pointerType==='pen'||(e.pointerType==='touch'&&e.pressure>0&&e.pressure!==.5)?Math.round(e.pressure*127):+$('velocity').value;play(e.target.dataset.bell?'bell':p.id,v);}});
 b.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;p.x=Math.max(10,Math.min(90,drag.px+(e.clientX-drag.x)/drag.w*100));p.y=Math.max(12,Math.min(83,drag.py+(e.clientY-drag.y)/drag.h*100));position(p);$('posx').value=p.x;$('posy').value=p.y;});
 for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{if(drag){drag=null;save();}});
 b.addEventListener('click',e=>{if(e.detail===0){select(p.id);if(!moving)play(p.id,+$('velocity').value);}});
}
select(selected);$('piece').onchange=e=>select(e.target.value);
for(const [id,key]of [['posx','x'],['posy','y'],['size','size'],['level','level'],['tune','tune']])$(id).oninput=e=>{const p=pieces.find(p=>p.id===selected);p[key]=+e.target.value;position(p);$('tunevalue').textContent=p.tune;save();};
$('mode').onclick=()=>{moving=!moving;$('mode').setAttribute('aria-pressed',moving);$('mode').textContent='Move kit: '+(moving?'on':'off');stage.classList.toggle('moving',moving);status.textContent=moving?'Drag a piece, or select it and adjust the sliders.':'Tap the kit or use the letter keys.';};
$('mirror').onclick=()=>{for(const p of pieces){p.x=100-p.x;position(p);}save();select(selected);const left=pieces.find(p=>p.id==='closed').x>50;$('mirror').textContent=left?'Right-handed setup':'Left-handed setup';};
$('reset').onclick=()=>{pieces=structuredClone(defaults);for(const p of pieces)position(p);save();select(selected);$('mirror').textContent='Left-handed setup';};
$('velocity').oninput=()=>{$('velvalue').value=$('velocity').value;};
async function enable(){if(!ctx){ctx=new AudioContext({latencyHint:'interactive'});master=ctx.createGain();master.gain.value=+$('volume').value;limiter=ctx.createDynamicsCompressor();limiter.threshold.value=-8;limiter.knee.value=4;limiter.ratio.value=12;limiter.attack.value=.002;limiter.release.value=.15;master.connect(limiter).connect(ctx.destination);}await ctx.resume();if(ready)return true;if(loading)return loading;
 $('start').disabled=true;loading=(async()=>{try{if(!manifest){const r=await fetch('samples.json');if(!r.ok)throw Error('Sample manifest unavailable');manifest=await r.json();}const files=[...new Set(Object.values(manifest).flat(2))];let done=0;
 // Bounded loading keeps mobile connections and decoder memory predictable.
 let index=0;await Promise.all(Array.from({length:4},async()=>{while(index<files.length){const f=files[index++];if(!buffers[f]){const r=await fetch(f);if(!r.ok)throw Error('Missing recording: '+f);buffers[f]=await ctx.decodeAudioData(await r.arrayBuffer());}status.textContent=`Loading acoustic recordings… ${++done}/${files.length}`;}}));ready=true;$('start').textContent='Sound ready';status.textContent='Ready. Tap a piece or use its key. Shift opens the hi-hat.';return true;}catch(e){status.textContent='Could not load all recordings. Check connection and tap Retry sound.';$('start').textContent='Retry sound';console.error(e);return false;}finally{$('start').disabled=false;loading=null;}})();return loading;}
function stopSet(set){if(!ctx)return;for(const voice of [...set]){voice.gain.gain.cancelScheduledValues(ctx.currentTime);voice.gain.gain.setTargetAtTime(0,ctx.currentTime,.012);try{voice.source.stop(ctx.currentTime+.06);}catch{}set.delete(voice);}}
function flash(id){const b=$('pad-'+id);if(!b)return;b.classList.add('hit');clearTimeout(b.flashTimer);b.flashTimer=setTimeout(()=>b.classList.remove('hit'),90);}
async function play(id,v=100){if(!ready){if(!await enable())return;}else if(ctx.state==='suspended')await ctx.resume();let actual=id;if(id==='closed'&&(shift||$('hatopen').checked))actual='open';const p=pieces.find(p=>p.id===id)||pieces.find(p=>p.id===(id==='bell'?'ride':'closed'));const bank=manifest[actual==='mid'?'high':actual];if(!bank)return;v=Math.max(1,Math.min(127,v));const layer=bank.length===3?(v<=30?0:v<80?1:2):bank.length===2?(v<70?0:1):0;const rrKey=actual+'-'+layer;const samples=bank[layer],file=samples[(round[rrKey]||0)%samples.length];round[rrKey]=(round[rrKey]||0)+1;
 if(actual==='closed'||actual==='pedal')stopSet(hatVoices);if(voices.size>96){const oldest=voices.values().next().value;try{oldest.source.stop();}catch{}voices.delete(oldest);}
 const source=ctx.createBufferSource(),gain=ctx.createGain(),pan=ctx.createStereoPanner();source.buffer=buffers[file];source.playbackRate.value=2**(p.tune/12);gain.gain.value=p.level*(.25+.75*v/127);pan.pan.value=Math.max(-.6,Math.min(.6,(p.x-50)/75));source.connect(gain).connect(pan).connect(master);const voice={source,gain};voices.add(voice);if(actual==='open')hatVoices.add(voice);if(p.type==='cymbal'&&actual!=='closed'&&actual!=='pedal')cymVoices.add(voice);source.onended=()=>{voices.delete(voice);hatVoices.delete(voice);cymVoices.delete(voice);source.disconnect();gain.disconnect();pan.disconnect();};source.start();flash(p.id);}
$('start').onclick=enable;$('volume').oninput=()=>{if(master)master.gain.setTargetAtTime(+$('volume').value,ctx.currentTime,.02);};$('test').onclick=()=>play(selected,+$('velocity').value);$('foot').onclick=()=>play('pedal',100);$('choke').onclick=()=>stopSet(cymVoices);$('panic').onclick=()=>stopSet(voices);$('hatopen').onchange=()=>{if(!$('hatopen').checked)play('pedal',80);};
window.addEventListener('keydown',e=>{if(e.key==='Shift'){shift=true;return;}if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(['BUTTON','SUMMARY','A'].includes(document.activeElement.tagName)&&[' ','Enter'].includes(e.key))return;if(e.repeat)return;if(e.key==='Escape'){stopSet(cymVoices);return;}if(moving)return;const key=e.key.toLowerCase();const p=pieces.find(p=>p.key===key);if(p){e.preventDefault();play(p.id,+$('velocity').value);}else if(key==='x'){e.preventDefault();play('pedal',100);}else if(key==='t'){e.preventDefault();play('bell',+$('velocity').value);}});
window.addEventListener('keyup',e=>{if(e.key==='Shift'){shift=false;if(!$('hatopen').checked&&ready)play('pedal',80);}});window.addEventListener('blur',()=>{shift=false;stopSet(hatVoices);});
if(pieces.find(p=>p.id==='closed').x>50)$('mirror').textContent='Right-handed setup';
