"use strict";
const ROLES=["DRUMS","PERC","BASS","MUSIC","VOCAL","TEXTURE"];
const NOTE_NAMES=["C","C♯","D","D♯","E","F","F♯","G","G♯","A","A♯","B"];
const $=s=>document.querySelector(s), lanesEl=$("#lanes");
const ROLE_ART={DRUMS:"pad_kick.png",PERC:"pad_shaker.png",BASS:"pad_tom.png",MUSIC:"pad_ride.png",VOCAL:"pad_clap.png",TEXTURE:"pad_fx.png"};
const PRESETS={clean:{filter:20000,drive:0,crush:0,delay:0,reverb:4,tremolo:0,compress:20},roots:{filter:5200,drive:34,crush:5,delay:8,reverb:14,tremolo:0,compress:62},mist:{filter:9800,drive:8,crush:0,delay:42,reverb:70,tremolo:18,compress:30},broken:{filter:6800,drive:72,crush:68,delay:17,reverb:12,tremolo:31,compress:76},cave:{filter:12500,drive:27,crush:22,delay:34,reverb:48,tremolo:8,compress:55},cosmic:{filter:15800,drive:18,crush:10,delay:62,reverb:82,tremolo:45,compress:38}};
let ctx, master, samples=[], lanes=ROLES.map(role=>({role,sample:null,locked:false,mute:false,solo:false,gain:.82,transpose:0}));
let playing=false,sources=[],startedAt=0,animation=0,fxRack=null;

function ensureAudio(){if(!ctx){ctx=new AudioContext();master=ctx.createGain();master.gain.value=+$("#master").value;fxRack=makeFxRack(ctx,ctx.destination);master.connect(fxRack.input);applyFx(fxRack)}return ctx.resume()}
function makeCurve(amount,steps=0){let n=2048,c=new Float32Array(n),k=amount*5;for(let i=0;i<n;i++){let x=i*2/(n-1)-1,y=amount?((1+k)*x)/(1+k*Math.abs(x)):x;c[i]=steps?Math.round(y*steps)/steps:y}return c}
function makeImpulse(ac,seconds=2.8){let len=Math.floor(ac.sampleRate*seconds),b=ac.createBuffer(2,len,ac.sampleRate);for(let c=0;c<2;c++){let d=b.getChannelData(c);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,2.5)}return b}
function makeFxRack(ac,destination){let input=ac.createGain(),filter=ac.createBiquadFilter(),drive=ac.createWaveShaper(),crush=ac.createWaveShaper(),trem=ac.createGain(),comp=ac.createDynamicsCompressor(),dry=ac.createGain(),delay=ac.createDelay(2),feedback=ac.createGain(),delayWet=ac.createGain(),verb=ac.createConvolver(),verbWet=ac.createGain(),lfo=ac.createOscillator(),lfoDepth=ac.createGain();filter.type="lowpass";drive.oversample="4x";verb.buffer=makeImpulse(ac);input.connect(filter).connect(drive).connect(crush).connect(trem).connect(comp);comp.connect(dry).connect(destination);comp.connect(delay);delay.connect(feedback).connect(delay);delay.connect(delayWet).connect(destination);comp.connect(verb).connect(verbWet).connect(destination);lfo.connect(lfoDepth).connect(trem.gain);lfo.start(0);return{input,filter,drive,crush,trem,comp,dry,delay,feedback,delayWet,verbWet,lfo,lfoDepth}}
function fxValues(){return{filter:+$("#fxFilter").value,drive:+$("#fxDrive").value,crush:+$("#fxCrush").value,delay:+$("#fxDelay").value,reverb:+$("#fxReverb").value,tremolo:+$("#fxTremolo").value,compress:+$("#fxCompress").value}}
function applyFx(rack=fxRack,values=fxValues()){if(!rack)return;let now=rack.input.context.currentTime,d=values.delay/100,r=values.reverb/100,t=values.tremolo/100;rack.filter.frequency.setValueAtTime(values.filter,now);rack.filter.Q.setValueAtTime(1+values.drive/28,now);rack.drive.curve=makeCurve(values.drive/100);rack.crush.curve=makeCurve(values.crush/300,values.crush?Math.max(2,32-Math.round(values.crush*.28)):0);rack.delay.delayTime.setValueAtTime((60/+$("#tempo").value)*(values.delay>55?.75:.5),now);rack.feedback.gain.setValueAtTime(Math.min(.68,d*.72),now);rack.delayWet.gain.setValueAtTime(d*.62,now);rack.verbWet.gain.setValueAtTime(r*.72,now);rack.lfo.frequency.setValueAtTime(.4+t*8,now);rack.lfoDepth.gain.setValueAtTime(t*.55,now);rack.trem.gain.setValueAtTime(1-t*.45,now);rack.comp.threshold.setValueAtTime(-8-values.compress*.34,now);rack.comp.ratio.setValueAtTime(1+values.compress*.11,now);rack.comp.attack.setValueAtTime(.004,now);rack.comp.release.setValueAtTime(.16,now)}
function updateFxReadouts(){let v=fxValues();$("#filterOut").textContent=v.filter>=1000?(v.filter/1000).toFixed(v.filter<10000?1:0)+"k":v.filter;for(let k of ["drive","crush","delay","reverb","tremolo","compress"])$("#"+k+"Out").textContent=v[k];applyFx()}
function loadPreset(name,values=PRESETS[name]){Object.entries(values).forEach(([k,v])=>$("#fx"+k[0].toUpperCase()+k.slice(1)).value=v);document.querySelectorAll("[data-preset]").forEach(b=>b.classList.toggle("active",b.dataset.preset===name));updateFxReadouts();let label=document.querySelector(`[data-preset="${name}"]`)?.textContent||"Random Wild";setStatus("Sound set: "+label,"Master effects updated. Play or export to hear the change.",100)}
function setStatus(title,detail="",pct=0){$("#statusTitle").textContent=title;$("#statusDetail").textContent=detail;$("#progress").style.width=pct+"%"}
function category(name,duration){let n=name.toLowerCase();if(/kick|snare|hat|clap|drum|break|beat/.test(n))return"DRUMS";if(/perc|shak|tamb|conga|bongo|rim/.test(n))return"PERC";if(/bass|sub|808/.test(n))return"BASS";if(/vox|vocal|voice|chant|acap/.test(n))return"VOCAL";if(/fx|noise|texture|amb|field|atmo|rise|impact/.test(n))return"TEXTURE";return duration<1.2?"PERC":"MUSIC"}
function estimateBpm(buffer){const data=buffer.getChannelData(0),sr=buffer.sampleRate,step=Math.max(1,Math.floor(sr/200)),env=[];for(let i=0;i<data.length;i+=step){let sum=0,end=Math.min(i+step,data.length);for(let j=i;j<end;j++)sum+=Math.abs(data[j]);env.push(sum/(end-i))}let best=0,bestLag=0;for(let bpm=70;bpm<=170;bpm++){let lag=Math.round((60/bpm)*200),score=0;for(let i=lag;i<env.length;i++)score+=env[i]*env[i-lag];if(score>best){best=score;bestLag=lag}}return bestLag?Math.round(60*200/bestLag):110}
function estimateKey(buffer){const data=buffer.getChannelData(0),sr=buffer.sampleRate,scores=new Float64Array(12),seconds=Math.min(buffer.duration,10),start=Math.floor(Math.max(0,(buffer.duration-seconds)/2)*sr),len=Math.floor(seconds*sr),window=Math.min(len,32768);for(let midi=36;midi<=83;midi++){let freq=440*Math.pow(2,(midi-69)/12),w=2*Math.PI*freq/sr,cos=2*Math.cos(w),s0=0,s1=0,s2=0;for(let i=0;i<window;i++){s0=data[start+i]+cos*s1-s2;s2=s1;s1=s0}scores[midi%12]+=s1*s1+s2*s2-cos*s1*s2}let best=0;for(let i=1;i<12;i++)if(scores[i]>scores[best])best=i;return best}
async function addFiles(fileList){await ensureAudio();const files=[...fileList].filter(f=>f.type.startsWith("audio/")||/\.(wav|mp3|ogg|m4a|aac|flac)$/i.test(f.name));if(!files.length){setStatus("No supported audio found","Choose a folder containing audio files.");return}samples=[];for(let i=0;i<files.length;i++){let f=files[i];setStatus("Analyzing your library",`${i+1} of ${files.length}: ${f.name}`,Math.round(i/files.length*100));try{let b=await ctx.decodeAudioData(await f.arrayBuffer()),bpm=estimateBpm(b),key=estimateKey(b);samples.push({name:f.name,buffer:b,duration:b.duration,bpm,key,role:category(f.name,b.duration),peak:peakOf(b)})}catch(e){console.warn("Skipped",f.name,e)}}finishAnalysis()}
function peakOf(b){let p=0,d=b.getChannelData(0),step=Math.max(1,Math.floor(d.length/15000));for(let i=0;i<d.length;i+=step)p=Math.max(p,Math.abs(d[i]));return p||1}
async function makeDemo(){await ensureAudio();samples=[];const specs=[["Forest Kick",55,"DRUMS"],["Branch Snare",180,"DRUMS"],["Pine Shaker",3200,"PERC"],["Deep Root Bass",55,"BASS"],["Moon Chords",220,"MUSIC"],["Night Voice",330,"VOCAL"],["Owl Air",880,"TEXTURE"]];for(let i=0;i<specs.length;i++){const [name,freq,role]=specs[i],dur=role==="DRUMS"?.55:role==="PERC"?2:4,b=ctx.createBuffer(1,ctx.sampleRate*dur,ctx.sampleRate),d=b.getChannelData(0);for(let n=0;n<d.length;n++){let t=n/ctx.sampleRate,phase=2*Math.PI*freq*t,beat=(t%(60/110));let env=role==="DRUMS"?Math.exp(-t*8):role==="PERC"?Math.exp(-beat*18):.35+.15*Math.sin(2*Math.PI*t/2);d[n]=(Math.sin(phase)+(role==="TEXTURE"?(Math.random()-.5)*1.2:0))*env*.35}samples.push({name:name+".wav",buffer:b,duration:dur,bpm:110,key:i%12,role,peak:peakOf(b)})}finishAnalysis()}
function finishAnalysis(){$("#fileCount").textContent=samples.length;$("#generateButton").disabled=!samples.length;setStatus("Library ready",`${samples.length} samples analyzed. Generate a mix to begin.`,100);render()}
function score(s,role){let target=+$("#tempo").value,tw=+$("#tempoWeight").value/100,hw=+$("#harmonyWeight").value/100,vw=+$("#varietyWeight").value/100,targetKey=$("#key").selectedIndex-1;let cat=s.role===role?2:s.role==="MUSIC"&&role==="TEXTURE"?.2:-.35,tempo=1-Math.min(1,Math.abs(s.bpm-target)/60),harmony=targetKey<0?1:1-Math.min(6,Math.abs(s.key-targetKey),12-Math.abs(s.key-targetKey))/6;return cat+tempo*tw+harmony*hw+Math.random()*vw}
function choose(role,except){return samples.filter(s=>s!==except).sort((a,b)=>score(b,role)-score(a,role))[0]||samples[0]}
function generate(one=-1){stop();lanes.forEach((l,i)=>{if((one<0&&!l.locked)||i===one)l.sample=choose(l.role,l.sample)});setStatus("Mix generated","Press play. Lock strong choices and reroll the rest.",100);render();enableTransport()}
function enableTransport(){let on=lanes.some(l=>l.sample);$("#playButton").disabled=!on;$("#stopButton").disabled=!on;$("#exportButton").disabled=!on}
function render(){lanesEl.innerHTML="";lanes.forEach((l,i)=>{let row=document.createElement("article");row.className=`lane ${l.sample?"":"empty"} ${l.locked?"locked":""}`;row.innerHTML=`<div class="role-pad"><img src="assets/${ROLE_ART[l.role]}" alt=""><span>${l.role}</span></div><div class="sampleName"><strong>${l.sample?escapeHtml(l.sample.name):"Waiting for mix"}</strong><small>${l.sample?`${l.sample.bpm} BPM · ${NOTE_NAMES[l.sample.key]} · ${l.sample.duration.toFixed(1)}s`:"No sample selected"}</small></div><div class="wave-wrap"><canvas width="700" height="116"></canvas></div><div class="controls"><input data-gain="${i}" aria-label="${l.role} volume" type="range" min="0" max="1" step=".01" value="${l.gain}"><button data-solo="${i}" class="${l.solo?"active":""}">SOLO</button><button data-mute="${i}" class="${l.mute?"active":""}">MUTE</button></div><div class="laneActions"><button data-lock="${i}" class="lock ${l.locked?"active":""}" title="${l.locked?"Unlock":"Lock"} this sample">Lock</button><button data-roll="${i}" class="roll" title="Reroll this lane" ${!samples.length?"disabled":""}>Reroll</button></div><div class="advancedRow"><label>Transpose <input data-pitch="${i}" type="range" min="-12" max="12" value="${l.transpose}"></label><label>Detected tempo <b>${l.sample?l.sample.bpm:"—"}</b></label><label>Detected key <b>${l.sample?NOTE_NAMES[l.sample.key]:"—"}</b></label><label>Peak <b>${l.sample?Math.round(l.sample.peak*100)+"%":"—"}</b></label></div>`;lanesEl.append(row);if(l.sample)drawWave(row.querySelector("canvas"),l.sample.buffer,l.role)})}
function drawWave(c,b,role){let x=c.getContext("2d"),d=b.getChannelData(0),mid=c.height/2,step=Math.max(1,Math.floor(d.length/c.width));x.clearRect(0,0,c.width,c.height);x.fillStyle="#07140f";x.fillRect(0,0,c.width,c.height);x.strokeStyle=role==="BASS"?"#9bc7a9":"#bed7aa";x.lineWidth=1.3;x.beginPath();for(let px=0;px<c.width;px++){let peak=0;for(let n=px*step;n<(px+1)*step&&n<d.length;n+=Math.max(1,step/20|0))peak=Math.max(peak,Math.abs(d[n]));x.moveTo(px,mid-peak*mid*.88);x.lineTo(px,mid+peak*mid*.88)}x.stroke()}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function loopLength(){return (+$("#bars").value)*4*60/(+$("#tempo").value)}
async function play(){await ensureAudio();stop(false);playing=true;startedAt=ctx.currentTime+.04;let anySolo=lanes.some(l=>l.solo);lanes.forEach(l=>{if(!l.sample||l.mute||(anySolo&&!l.solo))return;let src=ctx.createBufferSource(),g=ctx.createGain();src.buffer=l.sample.buffer;src.loop=true;src.playbackRate.value=(+$("#tempo").value/l.sample.bpm)*Math.pow(2,l.transpose/12);g.gain.value=l.gain;src.connect(g).connect(master);src.start(startedAt);sources.push(src)});$("#transportText").textContent="PLAYING";$("#playButton").classList.add("active");tick()}
function stop(update=true){sources.forEach(s=>{try{s.stop()}catch{}});sources=[];playing=false;cancelAnimationFrame(animation);$("#playhead").style.width="0";$("#position").textContent="1.1";$("#playButton").classList.remove("active");if(update)$("#transportText").textContent="STOPPED"}
function tick(){if(!playing)return;let p=((ctx.currentTime-startedAt)%loopLength()+loopLength())%loopLength()/loopLength();$("#playhead").style.width=(p*100)+"%";let beats=p*(+$("#bars").value)*4;$("#position").textContent=`${Math.floor(beats/4)+1}.${Math.floor(beats%4)+1}`;animation=requestAnimationFrame(tick)}
async function exportMix(){stop();setStatus("Rendering mix","Printing the mix and master effects to WAV.",20);let rate=44100,dur=loopLength(),off=new OfflineAudioContext(2,Math.ceil(rate*dur),rate),dest=off.createGain(),offRack=makeFxRack(off,off.destination),anySolo=lanes.some(l=>l.solo);dest.gain.value=+$("#master").value;dest.connect(offRack.input);applyFx(offRack);lanes.forEach(l=>{if(!l.sample||l.mute||(anySolo&&!l.solo))return;let s=off.createBufferSource(),g=off.createGain();s.buffer=l.sample.buffer;s.loop=true;s.playbackRate.value=(+$("#tempo").value/l.sample.bpm)*Math.pow(2,l.transpose/12);g.gain.value=l.gain;s.connect(g).connect(dest);s.start(0)});let b=await off.startRendering(),blob=wavBlob(b,$("#normalize").checked),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`VERQUINOX_${$("#tempo").value}BPM.wav`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);setStatus("Export complete",`${a.download} includes the active master effects.`,100)}
function wavBlob(b,norm){let ch=b.numberOfChannels,len=b.length,peak=0;for(let c=0;c<ch;c++)for(let i=0;i<len;i+=16)peak=Math.max(peak,Math.abs(b.getChannelData(c)[i]));let scale=norm&&peak>.001?.96/peak:1,ab=new ArrayBuffer(44+len*ch*2),v=new DataView(ab),p=0,txt=s=>{for(let c of s)v.setUint8(p++,c.charCodeAt(0))};txt("RIFF");v.setUint32(p,36+len*ch*2,true);p+=4;txt("WAVEfmt ");v.setUint32(p,16,true);p+=4;v.setUint16(p,1,true);p+=2;v.setUint16(p,ch,true);p+=2;v.setUint32(p,b.sampleRate,true);p+=4;v.setUint32(p,b.sampleRate*ch*2,true);p+=4;v.setUint16(p,ch*2,true);p+=2;v.setUint16(p,16,true);p+=2;txt("data");v.setUint32(p,len*ch*2,true);p+=4;for(let i=0;i<len;i++)for(let c=0;c<ch;c++){let s=Math.max(-1,Math.min(1,b.getChannelData(c)[i]*scale));v.setInt16(p,s<0?s*32768:s*32767,true);p+=2}return new Blob([ab],{type:"audio/wav"})}

lanesEl.addEventListener("input",e=>{let d=e.target.dataset;if(d.gain!==undefined)lanes[d.gain].gain=+e.target.value;if(d.pitch!==undefined)lanes[d.pitch].transpose=+e.target.value});
lanesEl.addEventListener("click",e=>{let d=e.target.dataset;if(d.lock!==undefined){lanes[d.lock].locked=!lanes[d.lock].locked;render()}if(d.roll!==undefined)generate(+d.roll);if(d.mute!==undefined){lanes[d.mute].mute=!lanes[d.mute].mute;render();if(playing)play()}if(d.solo!==undefined){lanes[d.solo].solo=!lanes[d.solo].solo;render();if(playing)play()}});
$("#folderInput").addEventListener("change",e=>addFiles(e.target.files));$("#demoButton").onclick=makeDemo;$("#generateButton").onclick=()=>generate();$("#playButton").onclick=()=>playing?stop():play();$("#stopButton").onclick=()=>stop();$("#panicButton").onclick=()=>{stop();if(ctx)ctx.suspend();setStatus("Audio stopped","Panic cleared every active sound.",0)};$("#master").oninput=e=>{if(master)master.gain.value=+e.target.value};$("#exportButton").onclick=exportMix;$("#advancedToggle").onclick=e=>{let on=!document.body.classList.contains("advanced-on");document.body.classList.toggle("advanced-on",on);$("#advancedPanel").hidden=!on;e.target.textContent=`Advanced: ${on?"On":"Off"}`;e.target.setAttribute("aria-pressed",on)};document.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.jump).scrollIntoView({behavior:"smooth"}));
document.querySelectorAll(".fx-grid input").forEach(x=>x.addEventListener("input",()=>{document.querySelectorAll("[data-preset]").forEach(b=>b.classList.remove("active"));updateFxReadouts()}));
document.querySelectorAll("[data-preset]").forEach(b=>b.onclick=()=>loadPreset(b.dataset.preset));
$("#randomPreset").onclick=()=>{let random={filter:500+Math.round(Math.random()*19500),drive:Math.round(Math.random()*86),crush:Math.round(Math.random()*78),delay:Math.round(Math.random()*72),reverb:Math.round(Math.random()*88),tremolo:Math.round(Math.random()*58),compress:20+Math.round(Math.random()*75)};loadPreset("random",random)};
$("#tempo").addEventListener("input",()=>applyFx());
updateFxReadouts();
render();
